name: Go CI Pipeline

# Define the events that trigger the workflow
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**' # Triggers on PRs targeting any branch
  push:
    branches-ignore:
      - main # Excludes pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GO111MODULE: on

    steps:
      # 1. Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.3' # Specify your Go version here

      # 3. Cache Go modules to speed up builds
      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # 4. Install dependencies using Makefile
      - name: Install Dependencies
        run: make install

      # 5. Run Linters
      - name: Run Linters
        run: make lint

      # 6. Check Code Formatting
      - name: Check Formatting
        run: make format

      # 7. Run Tests
      - name: Run Tests
        run: make test
